language: node_js
node_js: 'lts/*'
services:
  - docker
before_script:
  # Build the server container
  - cp package.json server/package.json
  - docker build -t fluxfail/server server/
  # Build the client container
  - npm run build
  - docker build -t fluxfail/client client/
  # Start the whole service
  - docker-compose up -d
  - docker-compose ps
