language: node_js
node_js: lts/*
services:
- docker
before_script: make travis
deploy:
  -
    provider: script
    script: bash spec/utils/docker_push
    on:
      branch: master
  -
    provider: script
    script: bash spec/utils/docker_push
    on:
      tags: true
env:
  global:
  - API_URL=https://api.flux.fail
  - secure: lfMBDnfEeC5W8XFKbTq9+ZDYTAw2a1LvSHg/48DqIEVaIQizynDH+2QzSChg6jl8UDhHlrM8HuQ/25AVQpubMJ1aSW+xEJk8KBDN5dBNT/JLN77S36ZPhWkLekH79SVKvuJ/c9+PhwGYq6/6VQq5xdkkqthz91iTwPLROtlj8PSF1vYxlfq84n2jK+1UXPY5WOcpFy5ihvTV+olQwlaH8cx4MVLENCHRNHspNeKWaLeuBKne19o1PXwAy6QYlJoR1NDqykjK67UycnC5kd1WYtGxjdX0Ja7WYUl2aohAz48Ui+YSj8WPz+/kCxBH3ckm7TzpME3qQQtwBAHJOb/bYtbXX/7lgdg2qjfbMWgpkU6bK8vw9yyblk2OPuekJpgS6sHYjptCnkqgT94/Lq2NYqlcVjf+2h2RxaYXV4ZZy84JGKd27s68h8fLmEHqwlUeeKAV7yeUG9azLvebPvX1zFCcURCvo1ovKvxGKE8vqB4CZsI2taThO2TlKOG8Nz3RDSknGZYJ6H8yQZI7LBQMdppCsFHbsoz90BTVGwfOxurJGG5iBD/KcknjrI1pJUqedz9OtXy/rbi5yPe5fbt7Ij4ZiSVkAGH40/fJNDQh/dZOF5cBM4o2E59+FSRWMfCCbUxF7FYWC87Kc/O/XuSwCtl1C4TyUo+JkiHmxOwHg80=
  - secure: YNIc2KvdE2vaFBE96nht4peKCv/6K1S67GoYvmsqFMIyxaCEP3gAMEqFtur5lTWxfBQupU5VKk/Bel9fp683/62yWVPHXWHjTUlYteTvYTInYqdgs/5MBV87CYdLTrd5dbkNP3j6TfyHoo8Z65UIad/VIx33K65EDt0D02mn6OhPYUEc1Ci02C5X2o+rtoMvnc0RXrfI8hSN5ivmjIZE96kIr9Ijy8yJWr5B7pde+SR5vpwNJkvyKTgVmN1iBPwu+4CzsY7KpxFBWMw3RaMz0dND0AGRBBHMg2IOfFZz8EA6C7o6gZIGsbVwruVx6SqH9wJg9hfMySMSYwB11K65YyV26ZbJSgMYky+YAUnHbctynFMTtgBdw/FcNcMZPBibK+1kNHqNFQ7IETuPetiRZBYhmXRs4cyr7UevRXSfdj+O+BjY+tIWLyi6AHF13P3/MYYY5SIXzNo1DEIO6ilXUNh3snC4HPI9INHXUIcJDFZMdVcAcim2nQOfsXUkT8VG5ida+MmYgZRWLJWklFrU9O/KdyslYH38zP1JefPqf1SEfIm7iDOXWIKnD1Q1dC00bmdR9tj0h8GynAi+0bQsMdc9tJP5Z6JRFpkYg8n1mfrMpySbT5aXHmRoFVNExp8tz30kvbEs/4kao9XIgQ56Fx25KPSwP0QOfC51F5Q9mD8=
notifications:
  email:
    on_success: never
    on_failure: always

