language: node_js
node_js: 'lts/*'
services:
  - postgresql
before_script:
  - psql -c 'create database fluxfail;' -U postgres
env:
  matrix:
    - DATABASE_URL=postgres://postgres:@localhost/fluxfail
