language: node_js
node_js: 'lts/*'
services:
  - docker
before_script:
  # Build the server container
  - cp package.json server/package.json
  - docker build -t fluxfail/server server/
  # Build the client container
  - npm run build
  - docker build -t fluxfail/client client/
  # Build the fake SMTP server used for testing
  - cp package.json spec/fakesmtp/package.json
  - docker build -t fluxfail/fakesmtp spec/fakesmtp/
  # Start the whole service
  - docker-compose up -d
  - docker-compose ps
  # Prepare the database
  - sleep 15
  - docker-compose exec server npm run migrate --no-interaction
