language: node_js
node_js: lts/*
services:
- docker
before_script:
- cp package.json server/package.json
- docker build -t fluxfail/server server/
- npm run build
- docker build -t fluxfail/client client/
- cp package.json spec/fakesmtp/package.json
- docker build -t fluxfail/fakesmtp spec/fakesmtp/
- docker-compose up -d
- docker-compose ps
- sleep 15
- docker-compose exec server npm run migrate --no-interaction
deploy:
  provider: script
  script: bash spec/utils/docker_push
  on:
    branch: master
env:
  global:
  - secure: lfMBDnfEeC5W8XFKbTq9+ZDYTAw2a1LvSHg/48DqIEVaIQizynDH+2QzSChg6jl8UDhHlrM8HuQ/25AVQpubMJ1aSW+xEJk8KBDN5dBNT/JLN77S36ZPhWkLekH79SVKvuJ/c9+PhwGYq6/6VQq5xdkkqthz91iTwPLROtlj8PSF1vYxlfq84n2jK+1UXPY5WOcpFy5ihvTV+olQwlaH8cx4MVLENCHRNHspNeKWaLeuBKne19o1PXwAy6QYlJoR1NDqykjK67UycnC5kd1WYtGxjdX0Ja7WYUl2aohAz48Ui+YSj8WPz+/kCxBH3ckm7TzpME3qQQtwBAHJOb/bYtbXX/7lgdg2qjfbMWgpkU6bK8vw9yyblk2OPuekJpgS6sHYjptCnkqgT94/Lq2NYqlcVjf+2h2RxaYXV4ZZy84JGKd27s68h8fLmEHqwlUeeKAV7yeUG9azLvebPvX1zFCcURCvo1ovKvxGKE8vqB4CZsI2taThO2TlKOG8Nz3RDSknGZYJ6H8yQZI7LBQMdppCsFHbsoz90BTVGwfOxurJGG5iBD/KcknjrI1pJUqedz9OtXy/rbi5yPe5fbt7Ij4ZiSVkAGH40/fJNDQh/dZOF5cBM4o2E59+FSRWMfCCbUxF7FYWC87Kc/O/XuSwCtl1C4TyUo+JkiHmxOwHg80=
  - secure: DCqcfdSXq5YG2adHVBUhf+cHWUsrvq+0e/ElKX90L/cnVFZJGDM44V+m+xC6negrCXOXXcoQ7vJifftugZU5dIQVl53xJQgyGEbTI2OurADUoaJSlcXhANsVz5/WQXwxu0DiTw0xmGi1s4TKTdeSCY9DuL6JpiUhSeVr7Fn/4zxwDiGEpD9zFyyXp3s/h5LjzYNhEH4qGDs5fD64MiPlN/36AyNZdxxaJ4YQleorwG7DT20obSZD8TBi5HtXRZe/ZsO8WEs8Ed049XeNhfm5IiyVNtdnL+G6MozDBE6lUTpFF/a9W61z1e0FOkzchF4Dt9Lvrl5IvM+U1V6f4pOplFAbjSRJYtV/Z4XL6btI491psjD8Mmzl8I/nJ3aZ/o0pT4RqImrzbitfGXQ9nek+lPK9lX1oLqUEWUw5RRlYfqn309BTWx7bp9uPsMga1LFh3vp6ZZv7Y555g+lCvcu/hnA9F2P9HN341ccDWQx6+5wuBAUK2LyrbeOGwU9FlK+bHNRuXuWPpZ6YVIdDAsoeQeqSNeKnd+14Is2pqpS956aN5oGycIzV77DmKWtIQ9guX0VO4QeLRomPoXo0Us8fh8XvPoYAvvyFIxVeN/ZQHya8C9V9M66e9ELKWDe3ywAom3wx6jukdATUrMCf7VmWTyA+KuOc2cjybRoj2Uzyv/Q=
