swagger: "2.0"
info:
  description: "This is the swagger file to genererate the api core for flux.fail"
  version: "1.0.0"
  title: "flux.fail"
  contact:
    email: "cem@sqrls.de"
host: "localhost:8081"
basePath: "/v1"
schemes:
- "https"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  Token:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
    xml:
      name: "Token"
  Delay:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user:
        type: "integer"
        format: "int64"
      created_at: 
        type: "string"
      location:
        type: "string"
    xml:
      name: "Delay"
paths: {}